<?php
/**
 * Страница "Форма настройки сессии пользователя".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью расширения модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>User session setup form</h1>
    <p>The session setup form can be called from:</p>
    <ul>
        <li>web application configuration panel;</li>
        <li>partition bar "Configuration / System";</li>
        <li>start, item "Configuration".</li>
    </ul>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><b>Session name.</b> Сбрасывает все настройки до значений по умолчанию (только после нажатия кнопки "Сохранить").</li>
        <li><b>Session lifetime, min.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Autostart.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Transparent SID support.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>SID only uses cookies.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Reset settings.</b> Resets all settings to default values (only after pressing the "Save" button).</li>
    </ul>
</article>