<?php
/**
 * Страница "Форма настройки сессии пользователя".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью расширения модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Форма настройки сессии пользователя</h1>
    <p>Форма настройки сессии можно вызывать из:</p>
    <ul>
        <li>панели конфигурации веб-приложения;</li>
        <li>панели разделов "Конфигурация / Система";</li>
        <li>пуск, пункт "Конфигурация".</li>
    </ul>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><b>Имя сессии.</b> Сбрасывает все настройки до значений по умолчанию (только после нажатия кнопки "Сохранить").</li>
        <li><b>Время жизни сессии, мин.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Автозапуск.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Прозрачная поддержка SID.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>SID использует только cookie.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Сбросить настройки.</b> Сбрасывает все настройки до значений по умолчанию (только после нажатия кнопки "Сохранить").</li>
    </ul>
</article>